// <auto-generated />
using System;
using ComputerStoreApplication.Logic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerStoreApplication.Migrations
{
    [DbContext(typeof(ComputerDBContext))]
    [Migration("20260129114641_PaymentSetNullable")]
    partial class PaymentSetNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerStoreApplication.Account.AdminAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ComputerStoreApplication.Account.CustomerAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("Id");

                    b.ToTable("AllComponentSpecifcations");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("ChipsetVendorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ChipsetVendorId");

                    b.ToTable("AllParts");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.CustomerShippingInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("State_Or_County_Or_Province")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerShippingInfos");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.BasketProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("CustomerId", "ProductId")
                        .IsUnique();

                    b.ToTable("BasketProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.DeliveryProvider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("DeliveryProviders");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DeliveryProviderId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxCosts")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DeliveryProviderId");

                    b.HasIndex("PaymentMethodId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderedProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.StoreProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ComputerPartId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Sale")
                        .HasColumnType("bit");

                    b.Property<bool>("SelectedProduct")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<Guid>("StoreProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ComputerPartId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BrandManufacturers");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.ChipsetVendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChipsetVendors");
                });

            modelBuilder.Entity("RAMRamProfileFeatures", b =>
                {
                    b.Property<int>("RAMsId")
                        .HasColumnType("int");

                    b.Property<int>("SupportedRamProfilesId")
                        .HasColumnType("int");

                    b.HasKey("RAMsId", "SupportedRamProfilesId");

                    b.HasIndex("SupportedRamProfilesId");

                    b.ToTable("RAMRamProfileFeatures");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification");

                    b.ToTable("CPUArchitectures", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification");

                    b.ToTable("CPUSockets");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification");

                    b.ToTable("EnergyClasses");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification");

                    b.ToTable("MemoryTypes");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification");

                    b.ToTable("RamProfiles");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.CPU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int?>("CPUArchitectureId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CPUCache")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Cores")
                        .HasColumnType("int");

                    b.Property<decimal?>("MemorySpeedGhz")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Overclockable")
                        .HasColumnType("bit");

                    b.Property<int?>("SocketId")
                        .HasColumnType("int");

                    b.Property<int?>("Threads")
                        .HasColumnType("int");

                    b.HasIndex("CPUArchitectureId");

                    b.HasIndex("SocketId");

                    b.ToTable("CPUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.GPU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<decimal?>("GPUFrequency")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MemorySizeGB")
                        .HasColumnType("int");

                    b.Property<decimal>("MemorySpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Overclock")
                        .HasColumnType("bit");

                    b.Property<int>("RecommendedPSUWattage")
                        .HasColumnType("int");

                    b.Property<int>("WattageConsumption")
                        .HasColumnType("int");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("GPUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.Motherboard", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<int?>("CPUArchitectureId")
                        .HasColumnType("int");

                    b.Property<int?>("CPUSocketId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Overclockable")
                        .HasColumnType("bit");

                    b.Property<bool>("Soundcard")
                        .HasColumnType("bit");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasIndex("CPUArchitectureId");

                    b.HasIndex("CPUSocketId");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.PSU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int?>("EnergyClassId")
                        .HasColumnType("int");

                    b.Property<decimal>("Wattage")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("EnergyClassId");

                    b.ToTable("PSUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.RAM", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int>("MemorySizePerStick")
                        .HasColumnType("int");

                    b.Property<decimal>("MemorySpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("RAMs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.Brand", "BrandManufacturer")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.ChipsetVendor", "ChipsetVendor")
                        .WithMany("Parts")
                        .HasForeignKey("ChipsetVendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BrandManufacturer");

                    b.Navigation("ChipsetVendor");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.CustomerShippingInfo", b =>
                {
                    b.HasOne("ComputerStoreApplication.Account.CustomerAccount", "Customer")
                        .WithMany("CustomerShippingInfos")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.BasketProduct", b =>
                {
                    b.HasOne("ComputerStoreApplication.Account.CustomerAccount", "Customer")
                        .WithMany("ProductsInBasket")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.Store.StoreProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.Order", b =>
                {
                    b.HasOne("ComputerStoreApplication.Account.CustomerAccount", "OrdCustomer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.Store.DeliveryProvider", "DeliveryProvider")
                        .WithMany()
                        .HasForeignKey("DeliveryProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.Store.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryProvider");

                    b.Navigation("OrdCustomer");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.OrderItem", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Store.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.Store.StoreProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.StoreProduct", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", "ComputerPart")
                        .WithMany("Products")
                        .HasForeignKey("ComputerPartId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.Brand", "Manufacturer")
                        .WithMany("StoreProducts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ComputerPart");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RAMRamProfileFeatures", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.RAM", null)
                        .WithMany()
                        .HasForeignKey("RAMsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", null)
                        .WithMany()
                        .HasForeignKey("SupportedRamProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.ComponentSpecification", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.CPU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", "CPUArchitecture")
                        .WithMany("CPUs")
                        .HasForeignKey("CPUArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.CPU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", "SocketType")
                        .WithMany("CPUs")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CPUArchitecture");

                    b.Navigation("SocketType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.GPU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.GPU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("GPUs")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.Motherboard", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", "CPUSocketArchitecture")
                        .WithMany("Motherboards")
                        .HasForeignKey("CPUArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", "CPUSocket")
                        .WithMany("Motherboards")
                        .HasForeignKey("CPUSocketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.Motherboard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("Motherboards")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CPUSocket");

                    b.Navigation("CPUSocketArchitecture");

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.PSU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", "EnergyClass")
                        .WithMany("PSUs")
                        .HasForeignKey("EnergyClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.PSU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyClass");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.RAM", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.RAM", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("RAMs")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Account.CustomerAccount", b =>
                {
                    b.Navigation("CustomerShippingInfos");

                    b.Navigation("Orders");

                    b.Navigation("ProductsInBasket");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Brand", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.ChipsetVendor", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", b =>
                {
                    b.Navigation("PSUs");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", b =>
                {
                    b.Navigation("GPUs");

                    b.Navigation("Motherboards");

                    b.Navigation("RAMs");
                });
#pragma warning restore 612, 618
        }
    }
}
