// <auto-generated />
using System;
using ComputerStoreApplication.Logic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ComputerStoreApplication.Migrations
{
    [DbContext(typeof(ComputerDBContext))]
    [Migration("20260109141536_TPTRelationsForClaritySake")]
    partial class TPTRelationsForClaritySake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPUArchitectureName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("CPUArchitectures");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPUSocketName")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("CPUSockets");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EnergyNameClass")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EnergyClasses");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("MemoryTypeName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("MemoryTypes");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RamProfileFeaturesType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.ToTable("RamProfiles");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int?>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("VendorId");

                    b.ToTable("ComputerPart");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerShippingInfoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.CustomerShippingInfo", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("State_Or_County_Or_Province")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("CustomerShippingInfos");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.CustomerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("Delivered")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("CustomerOrders");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.OrderProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerOrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("OrderedAmount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("CustomerOrderId");

                    b.ToTable("OrderedProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.StoreProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int?>("PartTypeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<bool>("Sale")
                        .HasColumnType("bit");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PartTypeId");

                    b.ToTable("StoreProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("RAMRamProfileFeatures", b =>
                {
                    b.Property<int>("RAMsId")
                        .HasColumnType("int");

                    b.Property<int>("SupportedRamProfilesId")
                        .HasColumnType("int");

                    b.HasKey("RAMsId", "SupportedRamProfilesId");

                    b.HasIndex("SupportedRamProfilesId");

                    b.ToTable("RAMRamProfileFeatures");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.CPU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int?>("CPUArchitectureId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CPUCache")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Cores")
                        .HasColumnType("int");

                    b.Property<decimal?>("MemorySpeedGhz")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Overclockable")
                        .HasColumnType("bit");

                    b.Property<int?>("SocketId")
                        .HasColumnType("int");

                    b.Property<int?>("Threads")
                        .HasColumnType("int");

                    b.HasIndex("CPUArchitectureId");

                    b.HasIndex("SocketId");

                    b.ToTable("CPUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.GPU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int>("MemorySizeGB")
                        .HasColumnType("int");

                    b.Property<decimal>("MemorySpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Overclock")
                        .HasColumnType("bit");

                    b.Property<int>("RecommendedPSUWattage")
                        .HasColumnType("int");

                    b.Property<int>("WattageConsumption")
                        .HasColumnType("int");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("GPUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.Motherboard", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<bool>("Bluetooth")
                        .HasColumnType("bit");

                    b.Property<int?>("CPUArchitectureId")
                        .HasColumnType("int");

                    b.Property<int?>("CPUSocketId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("Overclockable")
                        .HasColumnType("bit");

                    b.Property<bool>("Soundcard")
                        .HasColumnType("bit");

                    b.Property<bool>("Wifi")
                        .HasColumnType("bit");

                    b.HasIndex("CPUArchitectureId");

                    b.HasIndex("CPUSocketId");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("Motherboards", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.PSU", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int?>("EnergyClassId")
                        .HasColumnType("int");

                    b.Property<decimal>("Wattage")
                        .HasColumnType("decimal(18,2)");

                    b.HasIndex("EnergyClassId");

                    b.ToTable("PSUs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.RAM", b =>
                {
                    b.HasBaseType("ComputerStoreApplication.Models.ComputerComponents.ComputerPart");

                    b.Property<int>("MemorySizePerStick")
                        .HasColumnType("int");

                    b.Property<decimal>("MemorySpeed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("MemoryTypeId")
                        .HasColumnType("int");

                    b.HasIndex("MemoryTypeId");

                    b.ToTable("RAMs", (string)null);
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.Manufacturer", "Manufacturer")
                        .WithMany("Products")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.Vendor", "Vendor")
                        .WithMany("Parts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Manufacturer");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.CustomerShippingInfo", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Customer.Customer", "Customer")
                        .WithMany("CustomerShippingInfo")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.CustomerOrder", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Customer.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.OrderProduct", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Customer.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("ComputerStoreApplication.Models.Store.CustomerOrder", null)
                        .WithMany("Products")
                        .HasForeignKey("CustomerOrderId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.StoreProduct", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.Vendors_Producers.Manufacturer", "Manufacturer")
                        .WithMany("StoreProducts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", "PartType")
                        .WithMany("Products")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manufacturer");

                    b.Navigation("PartType");
                });

            modelBuilder.Entity("RAMRamProfileFeatures", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.RAM", null)
                        .WithMany()
                        .HasForeignKey("RAMsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.RamProfileFeatures", null)
                        .WithMany()
                        .HasForeignKey("SupportedRamProfilesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.CPU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", "CPUArchitecture")
                        .WithMany("CPUs")
                        .HasForeignKey("CPUArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.CPU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", "SocketType")
                        .WithMany("CPUs")
                        .HasForeignKey("SocketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CPUArchitecture");

                    b.Navigation("SocketType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.GPU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.GPU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("GPUs")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.Motherboard", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", "CPUSocketArchitecture")
                        .WithMany("Motherboards")
                        .HasForeignKey("CPUArchitectureId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", "CPUSocket")
                        .WithMany("Motherboards")
                        .HasForeignKey("CPUSocketId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.Motherboard", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("Motherboards")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CPUSocket");

                    b.Navigation("CPUSocketArchitecture");

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.PSU", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", "EnergyClass")
                        .WithMany("PSUs")
                        .HasForeignKey("EnergyClassId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.PSU", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EnergyClass");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.RAM", b =>
                {
                    b.HasOne("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", null)
                        .WithOne()
                        .HasForeignKey("ComputerStoreApplication.Models.ComputerComponents.RAM", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", "MemoryType")
                        .WithMany("RAMs")
                        .HasForeignKey("MemoryTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MemoryType");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUArchitecture", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.CPUSocket", b =>
                {
                    b.Navigation("CPUs");

                    b.Navigation("Motherboards");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.EnergyClass", b =>
                {
                    b.Navigation("PSUs");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComponentSpecifications.MemoryType", b =>
                {
                    b.Navigation("GPUs");

                    b.Navigation("Motherboards");

                    b.Navigation("RAMs");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.ComputerComponents.ComputerPart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Customer.Customer", b =>
                {
                    b.Navigation("CustomerShippingInfo");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Store.CustomerOrder", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Manufacturer", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("StoreProducts");
                });

            modelBuilder.Entity("ComputerStoreApplication.Models.Vendors_Producers.Vendor", b =>
                {
                    b.Navigation("Parts");
                });
#pragma warning restore 612, 618
        }
    }
}
